trigger:
  branches:
    include:
      - main  # Branche à surveiller

pool:
  vmImage: 'Default'  # Utilise une image d'agent Ubuntu

variables:
  GIT_EMAIL: "traorejames34@gmail.com"
  GIT_NAME: "BigJames3"

steps:
  - checkout: self
    displayName: 'Checkout du dépôt'

  # Étape de push vers GitHub
  - script: |
      git config --global user.email "$(GIT_EMAIL)"
      git config --global user.name "$(GIT_NAME)"

      git remote add github https://$(GH_TOKEN)@github.com/BigJames3/badgeuse_entreprise.git

      git pull --rebase github main || true
      git push github main
    displayName: 'Push vers GitHub'
